---
title: "Lab02-part2"
author: "Jose Ferreira"
date: "October 31, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Instalation

```{r, eval=FALSE}
#install.packages("caret")
```

Setting up a workspace
```{r ,warning=FALSE, message=FALSE}
setwd("~/git/data-analysis/lab02/part02/")
```

Building our dataframes



```{r ,warning=FALSE, message=FALSE}
test <- read.csv(("data/test.csv"))
train <- read.csv(("data/train.csv"))
```

Using the library carot

```{r ,warning=FALSE, message=FALSE}
library(caret)
library(dplyr)
library(lars)
library(ggplot2)
```

```{r ,warning=FALSE, message=FALSE}
train <- train %>%
  select(-cargo, -nome, -ocupacao)
test <- test %>%
  select(-cargo, -nome, -ocupacao)
```


#TODO: Deveria trocar os NA por a média da coluna

```{r}
media_partidos <- mean(train$recursos_de_partido_politico, na.rm = TRUE)
train$recursos_de_partidos[is.na(train$recursos_de_partido_politico)] <- media_partidos

media_comites <- mean(train$recursos_de_outros_candidatos.comites, na.rm = TRUE)
train$recursos_de_outros_candidatos.comites[is.na(train$recursos_de_outros_candidatos.comites)] <- media_comites

media_proprios <- mean(train$recursos_proprios, na.rm = TRUE)
train$recursos_proprios[is.na(train$recursos_proprios)] <- media_proprios


media_fisicas <- mean(as.numeric(train$recursos_de_pessoas_fisicas), na.rm = TRUE)
train$recursos_pessoas_fisicas[is.na(as.numeric(train$recursos_de_pessoas_fisicas))] <- media_fisicas

media_juridicas <- mean(train$recursos_de_pessoas_juridicas, na.rm = TRUE)
train$recursos_de_pessoas_juridicas[is.na(train$recursos_de_pessoas_juridicas)] <- media_juridicas

```



```{r ,warning=FALSE, message=FALSE}
train[is.na(train)] <- 0
test[is.na(test)] <- 0
```

# K-fold cross-validation
Creating the models
```{r ,warning=FALSE, message=FALSE}
fitControl <- trainControl(## 10-fold CV
                           method = "repeatedcv", # boot", "boot632", "cv", "repeatedcv", "LOOCV", "LGOCV"
                           number = 10,
                           ## repeated ten times
                           repeats = 10)

```

```{r ,warning=FALSE, message=FALSE}
preProcess = c("center", "scale","nzv" )
```

```{r ,warning=FALSE, message=FALSE}
model.lasso <- train(votos ~ ., 
               data = train,
               method = "lasso",
               metric = "RMSE",
               preProcess = preProcess,
               trControl = fitControl,
               na.action = na.exclude,
               tuneLength = 15)

model.lasso
```




```{r}
lasso_prediction <- predict(model.lasso,train)

lasso_data <- data.frame(pred = lasso_prediction, obs = train$votos)

lasso_cv<- round(defaultSummary(lasso_data),digits = 4)

lasso_cv
```


```{r}
lambda.grid <- expand.grid(lambda = seq(0, 2, by=0.1))
```



```{r ,warning=FALSE, message=FALSE}

#train <- as.data.frame(unclass(train))
model.ridge <- train(votos ~ ., 
               data = train,
               method = "ridge", # pode ser 'lasso'ldf
               tuneGrid = lambda.grid,
               metric = "RMSE",
               trControl = fitControl)

model.ridge

```


```{r}
ridge_prediction <- predict(model.ridge,train)

ridge_data <- data.frame(pred = ridge_prediction, obs = train$votos)

ridge_cv <- round(defaultSummary(ridge_data),digits = 4)

ridge_cv
```



```{r}
model.knn <- train(votos ~ ., 
               data = train,
               trControl = fitControl,
               method = "knn", # pode ser 'lasso'ldf
               metric = "RMSE",
               preProcess = preProcess)

model.knn
```

```{r}
knn_prediction <- predict(model.knn,train)

knn_data <- data.frame(pred = knn_prediction, obs = train$votos)

knn_cv <- round(defaultSummary(knn_data),digits = 4)

knn_cv
```
```{r}
knn_data
```

```{r}
plot(model.ridge, xlab = "Lambda", ylab = "RMSE")
```

```{r}
plot(model.lasso, xlab = "Lambda", ylab = "RMSE")
```

```{r}
plot(model.knn, ylab = "RMSE")
```


```{r}
ggplot(varImp(model.ridge))
```

```{r}
ggplot(varImp(model.lasso))
```

```{r}
ggplot(varImp(model.knn))
```


```{r}
newTrain <- train %>% select (-partido, -recursos_proprios,
                           -recursos_de_outros_candidatos.comites)
newTest <- test %>% select (-partido, -recursos_proprios,
                           -recursos_de_outros_candidatos.comites)
```

```{r}
grid <- expand.grid(k = model.lasso$bestTune)
control <- trainControl(method = "optimism_boot")
newModel.lasso <- train(votos ~ ., 
               data = newTrain,
               method = "lasso",
               tuneGrid = grid,
               trControl = control,
               preProcess = preProcess)
newModel.lasso 
```

```{r}
ggplot(varImp(newModel.lasso))
```

```{r}
newlasso_prediction <- predict(newModel.lasso)
newLasso_data <- data.frame(pred = newlasso_prediction, obs = train$votos)
new_lasso_cv <- round(defaultSummary(newLasso_data), digits = 4)
new_lasso_cv
```


```{r eval = FALSE}
newModel.lasso $xlevels[["ocupacao"]] <- union(newModel.lasso$xlevels[["ocupacao"]], levels(newTest$ocupacao))
prediction_ <- predict(newModel.lasso , newTest)
ID <- newTest %>%
  select(sequencial_candidato)
colnames(ID)[colnames(ID)=="sequencial_candidato"] <- "ID"
predicted_file <- ID
predicted_file$votos <- prediction_
predicted_file$votos[predicted_file$votos < 0] <- 0
write.csv(predicted_file, "sample_submission.csv", row.names=FALSE)
```