---
title: "Deputies Expenditures Analysis: Our Questions"
output: html_notebook
---

#TODO Here I gonna talk about the datas 
Link about it: http://www2.camara.leg.br/transparencia/acesso-a-informacao/copy_of_perguntas-frequentes/cota-para-o-exercicio-da-atividade-parlamentar 

For this lab we gonna need the following package to be installed
```{r}
install.packages("ggplot2")
install.packages("dplyr")
install.packages("tidyr")
install.packages("tidyverse")
install.packages("scales")
```

Loading the libraries
```{r}
 library(ggplot2)
 library(dplyr)
 library(tidyr)
 library(tidyverse)
 library(scales)

```

Set up the workspace folder

```{r}
setwd("~/git/data-analysis/Lab01")
```

Loading the data

```{r}
dados <- read_csv(("data/dadosCEAP.csv"))
```


```{r}
dados$valorGlosa <- as.numeric(sub(",", ".", dadosCEAP$valorGlosa, fixed = TRUE)) 
```


```{r}
#Need to fix that shit. Must sort by the dep_expenses before to filter
greater_expenses <- dados %>% 
  group_by(nomeParlamentar) %>%
  summarise(dep_expenses = sum(valorLíquido))



filter_expensies <- rbind(head(greater_expenses, 10), tail(greater_expenses, 10))
ggplot(filter_expensies, aes(y = dep_expenses, x = reorder(nomeParlamentar, dep_expenses)), top_n(x, 10)) + order(decreasing = TRUE) + scale_y_continuous(labels = comma) +
  geom_bar(stat="identity") +
  labs(title = "Deputies Expenses",
       x = "Deputies", y = "Expenses in R$") +
  coord_flip() 
```

